name: Lint
on: [push]

jobs:
  lint:
    name: Run Basic Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn eslint:check

      - name: Prettier
        run: yarn prettier:check

      - name: Build
        run: yarn build
