name: Locales
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Sync:
    name: Generate missing locales with chatgpt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: |
          yarn
      - name: Run generating script
        run: |
          yarn generate-locales
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
      - name: Configure git
        run: |
          git config --global user.name "turtlesocks-bot"
          git config --global user.email "turtlesocks-bot@users.noreply.github.com"
      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "changes_exist=true" >> $GITHUB_ENV
          fi
      - name: Commit and push changes
        if: ${{ env.changes_exist == 'true' }}
        run: |
          git add --all
          git commit --message "sync locales"
          git push
